### ISSUE TITLE
LCD menu issues (not scrolling)

### ISSUE THREAD

**Issue by AngelicLiver** [smithmi8/Arduino-Fireworks-Sequencer#1]
There appear to be issues scrolling through the menus, you can navigate to off-screen menu items and select them but the "view" does not refresh.

Thanks for sharing this project! I'm hoping I can contribute in some way.

**Comment by smithmi8** [comment]
I do not see this in any of my testing. What screen are you referring to exactly? Was there any modifications to the base code?

Also please note. I do not remember if I put it in the notes, when I was running this with MJG e-Matches, I discovered that I needed to change the fire time  to 0.100.  I found that some e-matches did not break the circuit causing a short.  The Battery used protected itself by resetting the board ending the shoot.  by setting the fire time t .1 second, everything fired off great.  I have not tested this with the Talon ignitors.
________________________________
From: Chris Durrant ***@***.***>
Sent: Monday, June 20, 2022 10:20 AM
To: smithmi8/Arduino-Fireworks-Sequencer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [smithmi8/Arduino-Fireworks-Sequencer] LCD menu issues (not scrolling) (Issue #1)


There appear to be issues scrolling through the menus, you can navigate to off-screen menu items and select them but the "view" does not refresh.

Thanks for sharing this project! I'm hoping I can contribute in some way.

**Comment by AngelicLiver** [comment]
I'm using a 1602 LCD with I2C module. Powers up great and you can navigate the menus with the rotary encoder but with asterisk denoting the selection moves off-screen. For example:

||*FIRE MODE = COM||
||TRIGGER = MANUA||

🔽

||*COMMON DELAY   ||
|| STEP RELATIVE        ||
............................................

It appears "FIRE ALL" is below this but the screen does not scroll.

Hope that makes sense?

**Comment by AngelicLiver** [comment]
Oh and no modifications to the base code. Just used your latest release on this Mega 2560.

**Comment by smithmi8** [comment]
Oh, that make sense. It was designed and written for a 2004 display. 20 characters wide by 4 rows.
The way the menus work you have to specify each line.  It would need to be completely re-written to run on a 1602 display.

________________________________

**Comment by AngelicLiver** [comment]
Ah ha! I suspected that might be the case but checked and double-checked the BOM and whilst it says 2004 it links to a 1602, whoops!

No problem, I'll order a 2004. Thanks.

**Comment by smithmi8** [comment]
FYI, I plan to update the software after the 4th of July to add an additional firing method.  Currently in version 2.0.2 there is a Common Delay, "Step delay" and a Fire All that I really do not recommend 🙂.  I am going to be changing the name of "Step" to "Time" for representing each cue has their own time delay.  "Step" will become a feature where each time the unit receives a signal from the input or remote, it will fire a cue then wait for the next signal.  Once it receives another signal, it will fire the next cue in the firing sequence. 1 - 32. The planned version release for this will become 2.0.3.
________________________________

**Comment by AngelicLiver** [comment]
That's awesome, thanks for all your hard work!
